name: GitHub Pages deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
      - name: npm install, build, and test
        run: |
          yarn
          yarn build
        env:
          CI: true

      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
