name: GitHub Pages deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          key: cache
          path: node_modules
      - name: npm install, build, and test
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          # Build directory to deploy
          build_dir: public
          # Commit author's name
          committer_name: BANO.notIT
          # Commit author's email
          committer_email: bano.notit@yandex.ru
